name: HerokuDeploy
on:
  push:
    branches:
      - master
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn clean compile assembly:single
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: vkrmaven
        path: target/
        retention-days: 5

  heroku-deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: ls1
        run: ls target
      - name: download
        uses: actions/download-artifact@v2
        with:
          name: vkrmaven
      - name: Login to Heroku Container registry
        uses: docker/login-action@v1
        with:
          registry: registry.heroku.com
          Username: aleksshru@gmail.com
          Password: ${{ secrets.HEROKU_API_KEY }}
      - name: Build and push docker container
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: registry.heroku.com/vkrmaven/web
      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          run: heroku container:push vkrmaven web
        run: heroku container:release -a vkrmaven web
